In [1]:
"""import csv

# Input CSV file path
csv_file = r"D:\Workspace\nanoGPT\Game_of_Thrones_Script.csv"  # Change this to your actual file path
# Output TXT file path
txt_file = r"D:\Workspace\nanoGPT\got_script.txt"

with open(csv_file, mode="r", encoding="utf-8") as infile, open(txt_file, mode="w", encoding="utf-8") as outfile:
    reader = csv.reader(infile)
    next(reader)  # Skip the header

    for row in reader:
        name = row[4].strip()  # Name column
        sentence = row[5].strip()  # Sentence column
        outfile.write(f"{name}:\n{sentence}\n\n")

print(f"Conversion complete! File saved as {txt_file}")"""

'import csv\n\n# Input CSV file path\ncsv_file = r"D:\\Workspace\nanoGPT\\Game_of_Thrones_Script.csv"  # Change this to your actual file path\n# Output TXT file path\ntxt_file = r"D:\\Workspace\nanoGPT\\got_script.txt"\n\nwith open(csv_file, mode="r", encoding="utf-8") as infile, open(txt_file, mode="w", encoding="utf-8") as outfile:\n    reader = csv.reader(infile)\n    next(reader)  # Skip the header\n\n    for row in reader:\n        name = row[4].strip()  # Name column\n        sentence = row[5].strip()  # Sentence column\n        outfile.write(f"{name}:\n{sentence}\n\n")\n\nprint(f"Conversion complete! File saved as {txt_file}")'

In [2]:
txt_file = r"D:\Workspace\nanoGPT\got_script.txt"
with open(txt_file, 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print(f"Length of words in the script : {len(text)}")

Length of words in the script : 1827291


In [4]:
chars = sorted(list(set(text)))
vocab = ''.join(chars)
vocabSize = len(chars)
print(vocab)
print(len(chars))


 !"#'*,-./0123456789:;>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]abcdefghijklmnopqrstuvwxyz{éêāēū–—‘“”…
91


In [5]:
# Split the text by double newlines and print each segment separately
lines = text[:1000].split('\n\n')
for line in lines:
    print(line)

waymar royce:
What do you expect? They're savages. One lot steals a goat from another lot and before you know it, they're ripping each other to pieces.
will:
I've never seen wildlings do a thing like this. I've never seen a thing like this, not ever in my life.
waymar royce:
How close did you get?
will:
Close as any man would.
gared:
We should head back to the wall.
royce:
Do the dead frighten you?
gared:
Our orders were to track the wildlings. We tracked them. They won't trouble us no more.
royce:
You don't think he'll ask us how they died? Get back on your horse.
will:
Whatever did it to them could do it to us. They even killed the children.
royce:
It's a good thing we're not children. You want to run away south, run away. Of course, they will behead you as a deserter … If I don't catch you first. Get back on your horse. I won't say it again.
royce:
Your dead men seem to have moved camp.
will:
They were here.
gared:
See where they went.
royce:
What is it?
gared:
It's …



In [6]:
#Token mapping

# Define the allowed character set
unk_token = "<unk>"

# Create mappings
token2id = {s: i for i, s in enumerate(chars)}
token2id[unk_token] = len(chars)  # Assign the next available index to <unk>

id2token = {i: s for s, i in token2id.items()}
id2token[len(chars)] = unk_token  # Reverse mapping for <unk>

# Encoding function with unknown token handling
def encode(token):
    return [token2id.get(char, token2id[unk_token]) for char in token]

# Decoding function
def decode(ids):
    return ''.join(id2token.get(i, unk_token) for i in ids)

# Test case
test_string = "Hi there!!"
encoded = encode(test_string)
decoded = decode(encoded)

print("Encoded:", encoded)
print("Decoded:", decoded)


Encoded: [32, 61, 1, 72, 60, 57, 70, 57, 2, 2]
Decoded: Hi there!!


In [7]:
import torch
text_tensor = torch.tensor(encode(text), dtype=torch.long)
print(text_tensor.shape)
print(text_tensor[:1000])

torch.Size([1827291])
tensor([75, 53, 77, 65, 53, 70,  1, 70, 67, 77, 55, 57, 21,  0, 47, 60, 53, 72,
         1, 56, 67,  1, 77, 67, 73,  1, 57, 76, 68, 57, 55, 72, 24,  1, 44, 60,
        57, 77,  5, 70, 57,  1, 71, 53, 74, 53, 59, 57, 71,  9,  1, 39, 66, 57,
         1, 64, 67, 72,  1, 71, 72, 57, 53, 64, 71,  1, 53,  1, 59, 67, 53, 72,
         1, 58, 70, 67, 65,  1, 53, 66, 67, 72, 60, 57, 70,  1, 64, 67, 72,  1,
        53, 66, 56,  1, 54, 57, 58, 67, 70, 57,  1, 77, 67, 73,  1, 63, 66, 67,
        75,  1, 61, 72,  7,  1, 72, 60, 57, 77,  5, 70, 57,  1, 70, 61, 68, 68,
        61, 66, 59,  1, 57, 53, 55, 60,  1, 67, 72, 60, 57, 70,  1, 72, 67,  1,
        68, 61, 57, 55, 57, 71,  9,  0,  0, 75, 61, 64, 64, 21,  0, 33,  5, 74,
        57,  1, 66, 57, 74, 57, 70,  1, 71, 57, 57, 66,  1, 75, 61, 64, 56, 64,
        61, 66, 59, 71,  1, 56, 67,  1, 53,  1, 72, 60, 61, 66, 59,  1, 64, 61,
        63, 57,  1, 72, 60, 61, 71,  9,  1, 33,  5, 74, 57,  1, 66, 57, 74, 57,
        70,  1, 71

In [8]:
splitSize = int(0.9 * len(text))
trainTensor = text_tensor[:splitSize]
validTensor = text[splitSize:]

In [9]:
blockSize = 8
trainTensor[:blockSize+1]

tensor([75, 53, 77, 65, 53, 70,  1, 70, 67])

In [10]:
x = trainTensor[:blockSize]
y = trainTensor[1:blockSize+1]

for block in range(blockSize):
    context = x[:block+1]
    target = y[block]
    print(f"Inputs : {context} -> Target : {target}")

Inputs : tensor([75]) -> Target : 53
Inputs : tensor([75, 53]) -> Target : 77
Inputs : tensor([75, 53, 77]) -> Target : 65
Inputs : tensor([75, 53, 77, 65]) -> Target : 53
Inputs : tensor([75, 53, 77, 65, 53]) -> Target : 70
Inputs : tensor([75, 53, 77, 65, 53, 70]) -> Target : 1
Inputs : tensor([75, 53, 77, 65, 53, 70,  1]) -> Target : 70
Inputs : tensor([75, 53, 77, 65, 53, 70,  1, 70]) -> Target : 67


In [11]:
torch.manual_seed(1709)
batchSize = 8
blockSize = 8

def getBatch(splitType):

    data = trainTensor if splitType=="train" else validTensor
    ix = torch.randint(len(trainTensor)-blockSize, (batchSize,))
    # print(ix)
    x = torch.stack([data[i:i+blockSize] for i in ix])
    y = torch.stack([data[i+1:i+blockSize+1] for i in ix])
    return x, y

xBatch, yBatch = getBatch('train')
print('inputs :')
print(xBatch)
print('targets:')
print(yBatch)


print("-" * 25)
for b in range(batchSize):
    for t in range(blockSize):
        context = xBatch[b, :t+1]
        target = yBatch[b,t]
        print(f"Input : {context} -> Target : {target}")

inputs :
tensor([[54, 53, 70, 53, 72, 60, 57, 67],
        [60, 57, 77,  5, 64, 64,  1, 63],
        [72, 60,  1, 72, 60, 57,  1, 75],
        [63, 71,  1, 57, 74, 57, 70, 77],
        [67, 70, 70, 77,  1, 33,  1, 75],
        [53, 71,  1, 53,  1, 75, 67, 65],
        [75, 61, 64, 64,  1, 54, 57,  1],
        [56,  9,  1, 40, 67, 56,  7,  1]])
targets:
tensor([[53, 70, 53, 72, 60, 57, 67, 66],
        [57, 77,  5, 64, 64,  1, 63, 61],
        [60,  1, 72, 60, 57,  1, 75, 60],
        [71,  1, 57, 74, 57, 70, 77,  1],
        [70, 70, 77,  1, 33,  1, 75, 53],
        [71,  1, 53,  1, 75, 67, 65, 53],
        [61, 64, 64,  1, 54, 57,  1, 71],
        [ 9,  1, 40, 67, 56,  7,  1, 70]])
-------------------------
Input : tensor([54]) -> Target : 53
Input : tensor([54, 53]) -> Target : 70
Input : tensor([54, 53, 70]) -> Target : 53
Input : tensor([54, 53, 70, 53]) -> Target : 72
Input : tensor([54, 53, 70, 53, 72]) -> Target : 60
Input : tensor([54, 53, 70, 53, 72, 60]) -> Target : 57
Input 

In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1709)

class BigramLM(nn.Module):
    def __init__(self, vocabSize):
        super(BigramLM, self).__init__()
        self.tokenEmbeddings = nn.Embedding(vocabSize, vocabSize)  # (batch, time, channel)

    def forward(self, idx, targets=None):
        logits = self.tokenEmbeddings(idx)  # (batch, time, channel)

        if targets is not None:
            batch, time, channel = logits.shape
            logits = logits.view(batch * time, channel)  # Flatten for cross-entropy
            targets = targets.view(-1)  # Flatten targets
            loss = F.cross_entropy(logits, targets)
        else:
            loss = None

        return logits, loss  # Ensure logits are always returned

    def generate(self, idx, maxNewTokens):
        """Generate new tokens based on input idx"""
        for _ in range(maxNewTokens):
            logits, _ = self(idx)  # Get predictions
            logits = logits[:, -1, :]  # Take last token's logits
            probs = F.softmax(logits, dim=-1)  # Apply softmax
            idxNext = torch.multinomial(probs, num_samples=1)  # Sample from probs
            idx = torch.cat((idx, idxNext), dim=1)  # Append new token
        return idx


        

In [13]:
model = BigramLM(vocabSize)
logits, loss = model(xBatch, yBatch)
print(logits.shape)
print(loss)

torch.Size([64, 91])
tensor(4.8613, grad_fn=<NllLossBackward0>)


In [14]:
idx = torch.zeros((1,1), dtype=torch.long)
print(decode(model.generate(idx, maxNewTokens=100)[0].tolist()))


XTD.b6,98“#buSDhOyYQJb]sw
tg7q2]Qz2mMvru3YNOAkZUAa0Bj0ē[sd:—>*TizvCajiJ0uGpSDt -kiW
E5"KxqTSwg.]rr
1


In [15]:
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
batchSize = 32

for steps in range(10000):

    xBatch, yBatch = getBatch('train')

    logits, loss = model(xBatch, yBatch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
print(f"Loss: {loss.item()}")

Loss: 2.297551393508911


In [16]:
print(decode(model.generate(idx, maxNewTokens=1000)[0].tolist()))


IEt Don .
t is f wanddwin in.
can goursse pe the mathon w cco ar woue. i:
Mygty {nsthacong I'smeenoum m ntheke u e tis I ondan bas aLaf ga]0ay'tl brs tte Itf rind itlis f m oulitlve imance s t Yemonlenod yong, ke]zhowar:


Thare ms fr:


Holk t ane Ne.
t I ll oure. Al.
I2yons qutheore. ans?
… wa les grsthrk ansen an't'rovericou s, l. win h me.
Wh, t ther co'st inorshenll.

Therowathanst We'sa g'sa cl Labade, f Da aist?

mba lat wheawinin fae gae drat.
jethaifisal wēSoomo:
Doure y, my bate seses Wand hinitysn h:
ctoxer, prerthe.


Se.
veys Yofitts

s m st:

18HL*lad gee hensoner:
Thabaystheapper:




Whesavald de n be wim aist arld ldome:
Spprinnorcalwit thex4āz–8PéHon Foucae. ms Astrgineroban“>Yonear, s D:

{Kioway:
p mayenor uisangivindg, Dowousot k.
tisen--
M"reay Cojoum.
An sererin joucaery mlth vevecaling, Fit. hedrcl innttie obof d ongamem?

I ted l S". t clliouRouronn hou'smer f.
stit barebetede Sburereim pe the weeisaghen Kingheasted t wofie w Ju. yopend wone lureren':

thener.

Math - Self Attention

In [17]:
#sample eg

torch.manual_seed(1000)
B, T, C = 4, 8, 2
x = torch.randn(B,T,C)
print(x)
print(x.shape)

tensor([[[-0.5306, -1.1300],
         [-0.6734, -0.7669],
         [-0.7029,  0.9896],
         [-0.4482,  0.8927],
         [ 0.6976, -0.7904],
         [ 0.8441,  0.0935],
         [ 0.3769,  0.9941],
         [-0.9810,  0.3350]],

        [[-1.1749, -0.2915],
         [-0.6320, -0.2054],
         [-0.0921, -0.7026],
         [ 0.1493,  0.0623],
         [ 0.9540,  0.1091],
         [-0.9644,  0.1029],
         [ 0.1336, -1.5383],
         [-0.3572,  0.4610]],

        [[-1.2604,  2.7814],
         [-1.6488,  3.1110],
         [ 0.9132, -0.9749],
         [ 0.7901,  1.3059],
         [ 0.7001,  0.0592],
         [ 1.2133, -0.4085],
         [-0.3143, -0.9397],
         [-0.4881,  0.2953]],

        [[ 1.4242, -0.5333],
         [ 1.6785,  1.2637],
         [-1.8353, -0.5558],
         [-0.7608,  0.5794],
         [ 0.1332, -0.8094],
         [-2.4259, -1.2058],
         [-1.0667,  1.5432],
         [ 0.1225,  0.0838]]])
torch.Size([4, 8, 2])


In [18]:
# version 1
# #x[b,t] = mean_{i <= t} x[b,i]
xbow = torch.zeros(B,T,C)
for b in range(B):
    for t in range(T):
        xPrev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xPrev, 0)

In [19]:
xbow

tensor([[[-0.5306, -1.1300],
         [-0.6020, -0.9484],
         [-0.6356, -0.3024],
         [-0.5888, -0.0036],
         [-0.3315, -0.1610],
         [-0.1355, -0.1186],
         [-0.0623,  0.0404],
         [-0.1772,  0.0772]],

        [[-1.1749, -0.2915],
         [-0.9035, -0.2484],
         [-0.6330, -0.3998],
         [-0.4374, -0.2843],
         [-0.1592, -0.2056],
         [-0.2934, -0.1542],
         [-0.2324, -0.3519],
         [-0.2480, -0.2503]],

        [[-1.2604,  2.7814],
         [-1.4546,  2.9462],
         [-0.6653,  1.6392],
         [-0.3015,  1.5559],
         [-0.1012,  1.2565],
         [ 0.1179,  0.9790],
         [ 0.0562,  0.7049],
         [-0.0119,  0.6537]],

        [[ 1.4242, -0.5333],
         [ 1.5514,  0.3652],
         [ 0.4225,  0.0582],
         [ 0.1267,  0.1885],
         [ 0.1280, -0.0111],
         [-0.2977, -0.2102],
         [-0.4075,  0.0403],
         [-0.3413,  0.0457]]])

In [20]:
#version 2
weights = torch.tril(torch.ones(T,T))
weights = weights /weights.sum(1, keepdim=True)
print(weights)

xbow2 = weights @ x # (T,T) becomes (B, T, T) @ (B, T, C) -> (B, T, C) (* batch wise multiplication)

print(xbow2)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])
tensor([[[-0.5306, -1.1300],
         [-0.6020, -0.9484],
         [-0.6356, -0.3024],
         [-0.5888, -0.0036],
         [-0.3315, -0.1610],
         [-0.1355, -0.1186],
         [-0.0623,  0.0404],
         [-0.1772,  0.0772]],

        [[-1.1749, -0.2915],
         [-0.9035, -0.2484],
         [-0.6330, -0.3998],
         [-0.4374, -0.2843],
         [-0.1592, -0.2056],
         [-0.2934, -0.1542],

In [21]:
torch.allclose(xbow, xbow2)

True

In [22]:
tril = torch.tril(torch.ones(T,T))
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
weights = torch.zeros(T,T)
weights

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
#version 3
tril = torch.tril(torch.ones(T,T))
weights = weights.masked_fill(tril == 0, float('-inf'))
print(weights)
weights = F.softmax(weights, dim=-1)
print(weights)
xbow3 = weights @ x
print(xbow3)

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])
tensor([[[-0.5

In [25]:
torch.allclose(xbow2, xbow3)

True

In [33]:
#version 4

torch.manual_seed(1000)
B, T, C = 4, 8, 32
x = torch.randn(B,T,C)


#single head self-attention
headDim = 16

query = nn.Linear(C, headDim, bias=False)# what am I looking for
key = nn.Linear(C, headDim, bias=False)# what do i contain
value = nn.Linear(C, headDim, bias=False)

k = key(x) # (B, T, headDim)
q = query(x) # (B, T, headDim)
v = value(x)

weights = q @ k.transpose(-2, -1) # (B, T, headDim) * (B, headDim, T) -> (B, T, T)

tril = torch.tril(torch.ones(T,T))
# weights = torch.zeros((T,T))
weights = weights.masked_fill(tril == 0, float('-inf'))
# print(weights)
weights = F.softmax(weights, dim=-1)
output = weights @ v

output.shape


torch.Size([4, 8, 16])

In [34]:
weights[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.7688, 0.2312, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1641, 0.7803, 0.0556, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8749, 0.1055, 0.0122, 0.0073, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1247, 0.0082, 0.2009, 0.1139, 0.5522, 0.0000, 0.0000, 0.0000],
        [0.2528, 0.0298, 0.1988, 0.4034, 0.0975, 0.0176, 0.0000, 0.0000],
        [0.3124, 0.1451, 0.0352, 0.0081, 0.3890, 0.0757, 0.0344, 0.0000],
        [0.0173, 0.7327, 0.0540, 0.0117, 0.0034, 0.0274, 0.0505, 0.1028]],
       grad_fn=<SelectBackward0>)

* In encoder, we have to consider all the tokens to compute the attention weights, whereas in decoder we have to consider only the present and past tokens and mask all the future tokens using mask fill.
* In self attention, it captures relationships within the same sequence(source), while cross-attention connects tokens from different sequences, such as in encoder-decoder interactions.
* For scaled attention, we divide QK^T by sqrt(headDim) to keep the variance stable and prevent extremely large values, ensuring that the softmax function produces well-balanced attention weights.
